name: Build and Trigger Central Deploy

on:
  push:
    branches:
      - master

jobs:
  build-and-trigger:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build Mule project
        env:
          ANYPOINT_CONNECTED_APP_CLIENT_ID: ${{ secrets.ANYPOINT_CONNECTED_APP_CLIENT_ID }}
          ANYPOINT_CONNECTED_APP_CLIENT_SECRET: ${{ secrets.ANYPOINT_CONNECTED_APP_CLIENT_SECRET }}
        run: mvn clean deploy -s settings.xml -B

      - name: Trigger deployment workflow in main repo
        run: |
          curl -X POST -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.PAT }}" \
          https://api.github.com/repos/aanyabajetha/maven-deployment-workflow/dispatches \
          -d "{\"event_type\":\"deploy-trigger\",\"client_payload\":{
          \"repo_owner\":\"aanyabajetha\",
          \"repo\":\"payment-validator-app-v1\",
          \"applicationName\":\"payment-validator-app-v1\",
          \"app_name\":\"payment-validator-app-v1-sandbox\",
          \"anypoint_uri\":\"https://anypoint.mulesoft.com\",
          \"anypoint_provider\":\"MC\",
          \"anypoint_env\":\"Sandbox\",
          \"anypoint_target\":\"Cloudhub-US-East-2\",
          \"replicas\":\"1\",
          \"vCores\":\"0.1\"
          }}"


